let questionList = [
    "What is the smallest thing for which you are grateful?",
    "Who has had the most positive impact on your life?",
    "If you could use a time machine, would you rather change something in the past or see something in the future?",
    "If you were an inanimate object, what would you be and why?",
    "If you could have grown up anywhere, where would it be?",
    "What is something you are terrible at but wish you could do well?",
    "What is the quality you admire most and dislike the most in a person?",
    "What was the most recent thing that made you cry?",
    "What is a movie that you could watch on repeat and never get tired of it?",
    "If you could be any mythical creature, what would you be?",
    "Which job have you had that has taught you the most?",
    "If you could change one thing about yourself physically what would it be?",
    "What single event or decision do you think most affected the rest of your life?",
    "What are you most proud of?",
    "Some historical figures have epithets attached to their names, like The Mad or The Wise. What would you like yours to be?",
    "What was the best year of your life? The worst?",
    "What has been the biggest change of heart you've had? Have you ever started off on one side of an issue and wound up on the other? What influenced that change?",
    "What is your biggest academic or work-related accomplishment?",
    "What is your biggest non-academic, non work-related accomplishment?",
    "What is something you've done/felt/seen/etc. that you wish you could experience again for the first time?",
    "If you could erase one thing or event from your memory, what would you choose?",
    "Is there something about you that people assume because of your appearance or demeanour? What is a trait or preference you have that people don't expect you to have?",
    "If you were a character in a movie, book, or television show, what genre would you live in?",
    "What is the hardest way you’ve learned an important lesson?",
    "What irrational fear do you have?",
    "What has been the happiest moment of your life so far?",
    "What is a childhood memory you have that you can describe vividly?",
    "Is there a song that, whenever heard, immediately reminds you of someone?",
    "How would you like to spend your birthday?",
    "What is the closest you’ve ever come to dying?",
    "What is your mantra?",
    "What is the most memorable meal you have ever had?",
    "What conspiracy theories do you believe are true?",
    "Do you believe in ghosts?",
    "Have you ever had a supernatural experience?",
    "Is there a character from a show, movie or book that you can relate to?",
    "If pay did not matter, what would be the job you would want most?",
    "What do you get the most compliments about?",
    "What is the most important quality, to you, in a relationship (Friend or significant other)?",
    "Do you have any habits you will never be able to break?",
    "What is your favorite word?",
    "What is your biggest flaw?",
    "What lessons have you had to constantly relearn?",
    "What was your favorite thing about the place that you grew up?",
    "Is there anything science or tech related that blows your mind or have a hard time wrapping your head around?",
    "If you could ask your future self one thing, what would it be?",
    "What would your biography or memoir be titled?",
    "What was the hardest decision you have ever made?",
    "What word would your best friend, parents or significant other use to describe you?",
    "If you could become famous, what would you want to be known for?",
    "Which season would you prefer to live in forever?",
    "Can you think of the best teacher you ever had? If so, why are they the best?",
    "What is something you never thought you’d be able to do until you actually did it?",
    "If you could go back and relive one day in your life without changing it, what day would you relive?",
    "If you could completely get rid of a single disease what would it be?",
    "If you could solve one political or social issue what would it be?",
    "What was the scariest moment of your life so far?",
    "If you lived in ancient times what would your job be?",
    "What is something everyone should try before they die?",
    "What do you want to exist that you know is not real?",
    "What is the most amount of pain you have ever experienced?",
    "Is there something you wish everyone knew about you?",
    "What trait do you admire in others that you do not have?",
    "Is there a question you hate being asked?",
    "What is your definition of success?",
    "Do you have a favorite piece of clothing?",
    "If you could play any instrument what would it be?",
    "If you could learn any language what would it be?",
    "Is there anything that you believe is too serious to joke about?",
    "What is your favorite project you have ever worked on?",
    "Are you currently pursuing what makes you happy?",
    "Are there any decisions you have made knowing it would be a mistake but still went through with it?",
    "In what ways do you think you are stubborn?",
    "What is a brief summary of your outlook on life?",
    "What are you most likely to be arrested for?",
    "Have you ever been arrested?",
    "Have you ever been pulled over by the police?",
    "If you could be any animal, what would it be?",
    "What is your least favorite thing about where you live?",
    "Does anyone beside you know your deepest secret and do you ever plan to tell anyone?",
    "What historical event would you like to have experienced?",
    "Do you believe in destiny or fate?",
    "If you could swap bodies with someone for one day, who would it be?",
    "What is the craziest thing you've ever done?",
    "Are you currently holding a grudge against someone?",
    "What little things annoy you?",
    "What is your biggest pet peeve?",
    "What historical figure do you most admire?",
    "What always makes you nostalgic?",
    "What would you like to accomplish before the year is over?",
    "What small and insignificant thing makes your day better?",
    "If you could live in any country, where would you live?",
    "When you are sick, what are some of the things you do to make yourself feel better?",
    "Is there a cause you strongly support?",
    "If you could make a large donation to any organization, which would you choose?",
    "Suddenly you're in a horror film, running from a masked murderer. Your only companion is the last person you texted, and your only weapon is whatever is currently closest to your left hand. What is the movie like and do you think you could survive?",
    "What was the greatest day of your life thus far?",
    "What was the worst day of your life thus far?",
    "In what way do you differ most from your parents?",
    "In what way do you differ most from your best friend?",
    "What is one thing you're proud you haven't done?",
    "What is something that's difficult for you but easy for most other people?",
    "What are you glad you learned as a child?",
    "What is something you want but will never have?",
    "If you could know for certain the answer to any question, what would that question be?",
    "What advice do you wish you'd received earlier?",
    "What was the hardest time of your life, and how did you make it through?",
    "What is the best compliment you've ever received?",
    "Is there a character trait that immediately turns you off?",
    "Who do you look up to the most in life?",
    "What expensive thing is absolutely worth the money?",
    "Would you change your name to anything different (first, middle or last)?",
    'How are you? No, really. How are you? Not "Fine," not "Good, thanks, and you?" How are you really? Now, today, at this moment?',
    "If you could live in any fictional world, where would it be and why?",
    "What has been the worst punishment you have received?",
    "Is there anything about yourself that is completely different than 10 years ago?",
    "What about yourself has not changed in the last 10 years?",
    "What wouldn’t you do for someone you love?",
    "If you could enhance one of your senses which would it be?",
    "What has been the best gift you have received?",
    "What is a completely rational fear you have?",
    "Who was the last person you spoke to on the phone and what did you talk about?",
    "What will always make you smile?",
    "What was the last song that got stuck in your head?",
    "If you could have one superpower, what would it be?",
    "Is there anything you’d be willing to die for?",
    "Is there anything you swore you would never do?",
    "Under what circumstances do you think you could kill someone, if any?",
    "What is your favorite memory with your best friend?",
    "What object best defines who you are?",
    "What is the strongest emotional connection you have had with someone (doesn’t have to be romantic)?",
    "Have you ever had a nemesis?",
    "What is the worst purchase you have ever made?",
    "How long do you think you could survive on a deserted island?",
    "What is the most obscure fact you know?",
    "Is there something you want to tell someone, but haven’t? Why haven’t you done it, and how do you think they would react if you told them?",
    "What subject could you teach a college course on? What would be the title of the course, and what units would you cover?",
    "Have you ever had a recurring dream or nightmare? What was it?",
    "What is something you fantasise about often?",
    "What do you find yourself thinking about just before you fall asleep?",
    "What is something you’re embarrassed to admit you enjoy? Why are you embarrassed about it?",
    "What if the first thing you hope people notice about you?",
    "What outfit makes you feel invincible?",
    "Have you ever hit “rock bottom”? What did it look and feel like to you? What situations or decisions led to it? How did you get out, or have you gotten out yet?",
    "What is the worst thing in your life that has resulted from a complete misunderstanding or miscommunication?",
    "What are you currently worrying about, if anything? What could happen to make you stop worrying about it?",
    "How do you think humanity will go extinct? When do you think it will happen?",
    "Is there a problem or situation for which you could use some advice?",
    "At a party, are you the social butterfly who chats with everyone, the intense conversationalist who gets really deep with someone, the person who showed up for the snacks, the person getting drunk, the person dancing, the host, the person hanging around the edges and not talking much, or someone else?",
    "A stranger is inhabiting your body for the day. What are some tips you’d give them?",
    "Who was your childhood hero? Do you still look up to them? Why or why not?",
    "What is your perfect meal?",
    "What are people not grateful enough for?",
    "What is the smallest thing that can ruin your day?",
    "What is the most recent thing (skill, technique, theory, subject, etc.) you taught yourself?",
    "What is something you wish people cared less about?",
    "What is something you wish people cared more about?",
    "How do you feel about the future right now?",
    "What immediately makes you think less of someone?",
    "What immediately makes you think more highly of someone?",
    "How would you want your children’s childhoods to be different from your own?",
    "What’s the quickest way to get you angry?",
    "How would your life change if you inherited $100,000 tomorrow?",
    "Do you have a nickname?",
    "What is the most beautiful view you have ever seen?",
    "How did you and your best friend meet?",
    "When do you feel like the best version of yourself?",
    "Coffee or tea?",
    "What type of music are you into?",
    "What’s your favorite way to spend a day off?",
    "What are your hobbies?",
    "What was the last book you read?",
    "What was the last TV show you watched?",
    "What is your favorite flavor of ice cream?",
    "Beach or mountains?",
    "Do you have any pet peeves?",
    "What activity instantly calms you?",
    "Would you rather cook or order food?",
    "What is your favorite board game?",
    "What would be the first thing you did if you won the lottery?",
    "How did you get into your profession?",
    "Do you think you will stay in your profession for a while?",
    'Are you more of a "work to live" or "live to work" type of person?',
    "What is the worst job you ever had?",
    "Do you have a side hustle or consider having one?",
    "How much time do you spend with your family?",
    "What is your definition of success?",
    "What is the first thing you look for in a partner or friend?",
    "How can someone earn your trust?",
    "How can someone lose your trust?",
    "Would you rather someone be honest and hurt your feelings or be told a lie to protect them?",
    "Do you believe in astrology?",
    "Do you believe in second chances?",
    "Do you believe in life on other planets?",
    "If you see a puddle on the ground, do you walk around, over or through it?",
    "If you could be any anima, what would you be?",
    "Do you hit the snooze button or do you wake up immediately?",
    "What's the first thing you do in the morning?",
    "Would you rather have scales or fur?",
    "What is the last thing you do at night?",
    "At a party, where can someone find you?",
    "What is your go to midnight snack?",
    "Would you rather have your dishes or laundry magically done?",
    "What is your least favorite chore?",
    "What TV shows are you into?",
    "What is your favorite drink?",
    "What is your dream car?",
    "What takes up too much of your time?",
    "What do you wish you knew more about?",
    "What mystery do you wish you knew the answer to?",
    "What is your favorite TV show genre?",
    "What is your favorite movie genre?",
    "What is something you like to do the old-fashioned way?",
    "Do you think with emotions or logic?",
    "Bulbasaur, Charmander or Squirtle?",
    "What kind of music do you like?",
    "What would you have for your last meal if you were on death row?",
    "Who was your best friend in 2nd grade?",
    "What do you wish you could do more of?",
    "Do you think you could win a fight against a bear?",
    "How do you think you'd do in a zombie apocalpyse?",
    "Were you ever in a school play? What was your role? What was the plot of the play? Did anything funny ever happen when you were on stage?",
    "What is the last concert you saw?",
    "Describe your mom's best friend.",
    "What was your favorite class you have ever taken?",
    "Tell your partner something that you like about them already.",
    "Is there something that you've dreamed of doing for a long time? Why haven't you done it?",
    "For what in your life do you feel most grateful?",
    "When did you last sing to yourself? To someone else?",
]

newQuestion = () => {
    let ranQuestion = questionList[Math.floor(Math.random()*questionList.length)];
    document.getElementById("question").innerHTML = ranQuestion;
}

toggleDisplay = () => {
    let nextbtn = document.getElementById("next")
    let startbtn = document.getElementById("start")
    startbtn.classList.toggle("hidden")
    nextbtn.classList.toggle("hidden")
}

document.getElementById("start").addEventListener("click", newQuestion);
document.getElementById("start").addEventListener("click", toggleDisplay);
document.getElementById("next").addEventListener("click", newQuestion);
